Repository fdnd-agency/oncollaboration, pull requests merged in 2025-04, with the labels that each got.

#73 Feature timestamps and featured webinar section
  src/lib/Assemblages/q-a.svelte
  src/lib/Blocks/comment.svelte
  src/lib/Constructions/footer.svelte
  src/routes/+layout.svelte
  src/routes/speakers/[slug]/+page.svelte
  src/routes/webinars/[slug]/+page.svelte
  static/images/kemenkessardjito.png
Labels: sprint 19

#76 Feature timestamp2
  src/lib/Blocks/comment.svelte
  src/routes/webinars/[slug]/+page.server.js
Labels: sprint 20

#77 timestamps, chapters and soe redesigns
  src/lib/Assemblages/q-a.svelte
  src/lib/Blocks/comment.svelte
  src/lib/Constructions/footer.svelte
  src/lib/Constructions/navigation.svelte
  src/routes/+layout.svelte
  src/routes/speakers/[slug]/+page.svelte
  src/routes/webinars/[slug]/+page.server.js
  src/routes/webinars/[slug]/+page.svelte
  static/css/global.css
  static/images/documents_icon.svg
  static/images/kemenkessardjito.png
Labels: sprint 20

#91 Code Refactor - Jason
  src/lib/Assemblages/q-a.svelte
  src/lib/Blocks/comment.svelte
  src/lib/Blocks/featured-webinar.svelte
  src/lib/Blocks/filter.svelte
  src/lib/Blocks/resources.svelte
  src/lib/Blocks/search.svelte
  src/routes/+layout.svelte
  src/routes/+page.svelte
  src/routes/contourings/+page.svelte
  src/routes/profile/+page.svelte
  src/routes/search/+page.svelte
  src/routes/speakers/[slug]/+page.svelte
  src/routes/webinars/+page.svelte
  src/routes/webinars/[slug]/+page.svelte
  static/css/global.css
  static/fonts/Poppins-Bold-subset.ttf
Labels: bouwen
