Repository fdnd-agency/oncollaboration, pull requests merged in 2025-06, with the labels that each got.

#142 cta has been finished for mobile
  src/app.html
  src/lib/Bricks/Button.svelte
  src/lib/Bricks/arrow.svelte
  src/lib/Constructions/cta.svelte
  src/lib/index.js
  src/routes/+page.svelte
  static/css/global.css
Labels: bouwen, Home, sprint 20

#145 feature-nav-lesleyV1.0.4(Validation and bg navbar)
  src/lib/Constructions/navigation.svelte
Labels: must have, bouwen, Home, Release candidate

#148 ver 1.0 footer mobile
  src/lib/Constructions/footer.svelte
Labels: sprint 20

#149 Fix nav syling lesley
  src/lib/Constructions/navigation.svelte
Labels: must have, bouwen, Home, Release candidate

#150 text color fix
  src/lib/Bricks/Button.svelte
Labels: must have, bouwen, Home, Release candidate

#152 font changes based on global css
  src/lib/Constructions/article.svelte
Labels: must have, bouwen, Home, Release candidate

#157 doctors-united change based on global css
  src/lib/Constructions/doctors-united.svelte
Labels: must have, bouwen, Home, Release candidate
